"""Medical Interview (multi-turn questioning) models.

LLM-driven dynamic interview engine.
The Agent decides WHAT to ask next based on the patient's chief complaint
and already-collected info, rather than following a fixed script.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from typing import Any

from pydantic import BaseModel, Field


@dataclass
class QuestionTemplate:
    """A single interview question."""

    question_id: str
    question: str
    type: str  # "choice" or "text"
    options: list[str] = field(default_factory=list)
    hint: str = ""
    allow_skip: bool = True


@dataclass
class InterviewState:
    """Snapshot of an ongoing interview stored in AgentSession.context."""

    collected_info: dict[str, Any] = field(default_factory=dict)
    asked_questions: list[str] = field(default_factory=list)
    current_question_id: str | None = None
    is_sufficient: bool = False
    max_questions: int = 6
    chief_complaint: str = ""  # 用户原始主诉

    def to_dict(self) -> dict[str, Any]:
        return {
            "collected_info": self.collected_info,
            "asked_questions": self.asked_questions,
            "current_question_id": self.current_question_id,
            "is_sufficient": self.is_sufficient,
            "max_questions": self.max_questions,
            "chief_complaint": self.chief_complaint,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "InterviewState":
        return cls(
            collected_info=data.get("collected_info", {}),
            asked_questions=data.get("asked_questions", []),
            current_question_id=data.get("current_question_id"),
            is_sufficient=data.get("is_sufficient", False),
            max_questions=data.get("max_questions", 6),
            chief_complaint=data.get("chief_complaint", ""),
        )


# ---------------------------------------------------------------------------
# LLM-driven interview decision schema
# ---------------------------------------------------------------------------

class NextQuestionSchema(BaseModel):
    """Schema for the next question generated by LLM."""

    question_id: str = Field(..., description="唯一标识符，用于追踪")
    question: str = Field(..., description="呈现给患者的问题文本")
    type: str = Field(..., pattern="^(choice|text)$", description="问题类型")
    options: list[str] = Field(default_factory=list, description="选择题选项（type=choice 时必填）")
    hint: str = Field(default="", description="给患者的提示")
    allow_skip: bool = Field(default=True, description="是否允许跳过")


class InterviewDecision(BaseModel):
    """LLM output: whether we have enough info and what to ask next."""

    sufficient: bool = Field(..., description="是否已收集足够信息进行初步诊断")
    next_question: NextQuestionSchema | None = Field(default=None, description="下一个问题（sufficient=false 时必填）")
    reasoning: str = Field(default="", description="问诊决策的简要说明")


# ---------------------------------------------------------------------------
# Prompt for dynamic interview generation
# ---------------------------------------------------------------------------

INTERVIEW_SYSTEM_PROMPT = """你是一位经验丰富的全科医生，正在进行患者初诊问诊。

## 核心原则
1. **针对主诉**：问题必须围绕患者主诉展开，不问无关问题
2. **循序渐进**：从最关键的信息开始，逐步深入
3. **动态调整**：根据患者回答决定下一个问题，不要按固定脚本
4. **医学专业性**：使用准确的医学术语，但呈现给患者时通俗易懂

## 问诊策略
- 首先确认核心信息：症状的性质、部位、持续时间、严重程度
- 根据主诉选择追问方向：
  * 腹痛 → 位置、性质、放射痛、伴随症状
  * 头痛 → 部位、性质、触发因素、伴随症状
  * 发热 → 热度、持续时间、伴随症状
  * 咳嗽 → 性质、持续时间、喷出物
- 关注危险信号：如果回答中暗示严重疾病，应该提前结束问诊并强调紧急就医

## 输出格式
请严格返回 JSON，不要有任何额外文本。格式如下：
```json
{
  "sufficient": false,
  "next_question": {
    "question_id": "唯一标识",
    "question": "问题文本",
    "type": "choice 或 text",
    "options": ["选项1", "选项2"],
    "hint": "提示文本",
    "allow_skip": true
  },
  "reasoning": "决策说明"
}
```

规则：
- sufficient=true 时，next_question 必须为 null
- type="choice" 时，options 必须至少有 2 个选项
- type="text" 时，options 应为空数组 []
- 问题要简洁明了，避免专业术语堆码
"""


def _build_interview_prompt(state: InterviewState) -> str:
    """Build the user prompt for LLM interview decision."""
    lines = [f"患者主诉：{state.chief_complaint or '未知'}"]
    lines.append("")

    if state.collected_info:
        lines.append("已收集的问诊信息：")
        for k, v in state.collected_info.items():
            lines.append(f"  - {k}: {v}")
        lines.append("")
    else:
        lines.append("尚未收集任何问诊信息。")
        lines.append("")

    lines.append(f"已问过 {len(state.asked_questions)} 个问题，最多可问 {state.max_questions} 个。")
    if state.asked_questions:
        lines.append(f"已问问题 ID: {', '.join(state.asked_questions)}")
    lines.append("")

    if len(state.asked_questions) >= state.max_questions:
        lines.append("已达到最大问诊数量上限，请判定信息是否足够。")
    else:
        lines.append("请判断当前信息是否足够进行初步诊断，如果不足够，请生成下一个最关键的问题。")

    return "\n".join(lines)


def _extract_json(text: str) -> dict[str, Any]:
    """Extract JSON from LLM response (handles markdown code blocks)."""
    text = text.strip()
    # Try to find JSON in markdown code block
    if "```json" in text:
        match = re.search(r"```json\s*(.*?)\s*```", text, re.DOTALL)
        if match:
            text = match.group(1).strip()
    elif "```" in text:
        match = re.search(r"```\s*(.*?)\s*```", text, re.DOTALL)
        if match:
            text = match.group(1).strip()
    return json.loads(text)


# ---------------------------------------------------------------------------
# Dynamic interview engine (replaces fixed question bank)
# ---------------------------------------------------------------------------

class DynamicInterviewEngine:
    """Uses LLM to decide what to ask next based on patient context."""

    def __init__(self, llm_service: Any) -> None:
        self.llm = llm_service

    async def decide_next(
        self,
        state: InterviewState,
    ) -> tuple[QuestionTemplate | None, InterviewState]:
        """Ask LLM to decide the next question or if we have enough info.

        Returns:
            (next_question, updated_state) — next_question is None if sufficient.
        """
        prompt = _build_interview_prompt(state)

        try:
            response = await self.llm.chat(
                messages=[{"role": "user", "content": prompt}],
                system_prompt=INTERVIEW_SYSTEM_PROMPT,
                temperature=0.3,
                max_tokens=1024,
            )

            raw = _extract_json(response.content)
            decision = InterviewDecision.model_validate(raw)

            if decision.sufficient or len(state.asked_questions) >= state.max_questions:
                state.is_sufficient = True
                state.current_question_id = None
                return None, state

            if decision.next_question is None:
                # LLM says not sufficient but gave no question — fallback
                state.is_sufficient = True
                state.current_question_id = None
                return None, state

            q = decision.next_question
            # Validate: don't repeat asked questions
            if q.question_id in state.asked_questions:
                # LLM generated a duplicate — generate a unique id
                q.question_id = f"{q.question_id}_{len(state.asked_questions)}"

            question = QuestionTemplate(
                question_id=q.question_id,
                question=q.question,
                type=q.type,
                options=q.options if q.type == "choice" else [],
                hint=q.hint,
                allow_skip=q.allow_skip,
            )

            state.current_question_id = question.question_id
            return question, state

        except Exception:
            # LLM failed — fallback to a generic "any other symptoms?" question
            if len(state.asked_questions) >= 3:
                state.is_sufficient = True
                state.current_question_id = None
                return None, state

            fallback = QuestionTemplate(
                question_id=f"fallback_{len(state.asked_questions)}",
                question="还有其他不适或想补充说明的吗？",
                type="text",
                hint="可以描述任何未被问到的症状或情况",
            )
            state.current_question_id = fallback.question_id
            return fallback, state
